import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "src/components/toastProvider/ToastProvider";
import Footer from "src/layouts/footer/Footer";
import Header from "src/layouts/header/Header";
import Provider from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <ToastProvider />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
